#!/bin/bash
echo "export file lists"
echo "# Ethiopian Books" >> README.md
echo "## [Please follow me](https://github.com/hmhard)" >> README.md
echo "## Star this repository" >> README.md
echo "| # | Name | Pages |" >> README.md
echo "| -- | -- | -- |" >> README.md
INDEX=1
for filename in files/*.pdf; do
    FILE=${filename//_/ }
    FILE=${FILE//files\//}
    FILE=${FILE//\.pdf/}
    PAGES=$(pdfinfo $filename | awk '/^Pages:/ {print $2}') 

    echo "| ${INDEX} | [${FILE}](${filename// /_}) | ${PAGES} | "  >> README.md 
    # echo "" >> README.md
    let INDEX=${INDEX}+1
done
echo " | -- | -- | -- | " >> README.md